version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: flashcard_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: japanese_flashcard
      POSTGRES_USER: flashcard_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/init:/docker-entrypoint-initdb.d
    networks:
      - flashcard_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flashcard_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: japanese_flashcard
      DB_USER: flashcard_user
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - flashcard_network

  # Frontend (Optional - nếu cần serve static files)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flashcard_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - flashcard_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: flashcard_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - flashcard_network

volumes:
  postgres_data:
    driver: local

networks:
  flashcard_network:
    driver: bridge